services:
  api: &main_app
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    image: gritter:${GRITTER_VERSION:-latest}
    restart: always
    ports:
      # Exposes application port.
    - "8000:8000"
    env_file:
      - path: .env
        required: false
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      GRITTER_HOST: 0.0.0.0
      GRITTER_RELOAD: "True"
      GRITTER_DB_HOST: gritter-db
      GRITTER_DB_PORT: 5432
      GRITTER_DB_USER: gritter
      GRITTER_DB_PASS: gritter
      GRITTER_DB_BASE: gritter
      GRITTER_RABBIT_HOST: gritter-rmq
      GRITTER_REDIS_HOST: gritter-redis
      GRITTER_MINIO_HOST: gritter-minio
      GRITTER_MINIO_PORT: 9000
      GRITTER_MINIO_ACCESS_KEY: minioadmin
      GRITTER_MINIO_SECRET_KEY: minioadmin
    volumes:
      - .:/app/src/

  db:
    image: postgres:18.3-trixie
    hostname: gritter-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "gritter"
      POSTGRES_USER: "gritter"
      POSTGRES_DB: "gritter"
    volumes:
      - gritter-db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: pg_isready -U gritter
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    <<: *main_app
    restart: "no"
    command: alembic upgrade head
    volumes: []
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:8.4.0
    hostname: "gritter-redis"
    restart: always
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rmq:
    image: rabbitmq:4.2.1-management-alpine
    hostname: "gritter-rmq"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50

  minio:
    image: minio/minio:latest
    hostname: "gritter-minio"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 3s
      timeout: 3s
      retries: 50
    volumes:
      - gritter-minio-data:/data


volumes:
  gritter-minio-data:
  gritter-db-data:
    name: gritter-db-data
